### ISSUE TITLE
Honor custom "basepath"

### ISSUE THREAD

**Issue by zoernert** [DoubleBastionAdmin/sip-trip-phone#1]
The current release assumes Nextcloud to be installed in the root path. 

So the pop-up gets opened using the URL like: https://server.com/apps/sip_trip_phone/phone/index.html and should be https://nextcloud.stromdao.de/[basepath]apps/sip_trip_phone/phone/index.html

**Comment by DoubleBastionAdmin** [comment]
Yes, SIP Trip Phone assumes that Nextcloud is served on a subdomain like `cloud.domain.com` and not on a subdirectory like `domain.com/nextcloud/`. I'll have to specify this in the app description, in the app store.

Are you using Nginx or Apache ?

**Comment by DoubleBastionAdmin** [comment]
Version 1.0.5 of SIP Trip Phone solves this problem. It works when Nextcloud is served on a subdomain, but also when it's served on a subdirectory with a custom basepath. It has been tested in both situations with both Nginx and Apache.
Detailed documentation on how to install SIP Trip Phone and how to connect it directly to the SIP provider or indirectly, via Asterisk, can be found here: https://www.doublebastion.com/install-nextcloud/#install-sip-trip-phone . We recommend Nginx, but if you use Apache, it has to be configured as described here: https://www.doublebastion.com/apache-configuration-for-nextcloud/

**Comment by zoernert** [comment]
At least on the first run I had the same issue - but it could be that my apache config is still incorrect (I get redirected to the dashboard of nextcloud in the popup)

**Comment by DoubleBastionAdmin** [comment]
Please make sure you have enabled 'pretty URLs' in your Nextcloud configuration. On this page: https://www.doublebastion.com/apache-configuration-for-nextcloud/#configure-apache-nextcloud-subdirectory you can see the correct Apache configuration for Nextcloud (including the lines needed by SIP Trip Phone).

Pretty URLs have the `index.php`part removed. As explained on that page, to enable pretty URLs for Nextcloud served by Apache on a subdirectory, add the following two lines below the `version` line in your Nextcloud `config.php` file:
```
  'overwrite.cli.url' => 'https://example.com/nextcloud',
  'htaccess.RewriteBase' => '/nextcloud',
```
where `example.com` (or `www.example.com`) is your domain and `nextcloud` is the subdirectory that you want to use to serve Nextcloud.

Also, update the `.htaccess` file by running the following command:
```
sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess
```
Please let me know if you solved the problem.

**Comment by DoubleBastionAdmin** [comment]
I deduce that you managed to add the lines needed by SIP Trip Phone to your Apache configuration and that the application started as expected. Therefore, if there are no other problems, this issue will be closed.
